version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  catalog-service:
    build: ./catalog-service
    ports:
      - "5001:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/farmacia
    depends_on:
      - mongo

  inventory-service:
    build: ./inventory-service
    ports:
      - "5002:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/farmacia
    depends_on:
      - mongo

  orders-service:
    build: ./orders-service
    ports:
      - "5003:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/farmacia
    depends_on:
      - mongo
